In [1]:
from load_data import *
import pandas as pd
import numpy as np

In [2]:
loader = LoadData()

In [3]:
loader.load_celldyn()

In [4]:
loader.preprocess()

In [5]:
df = loader.retrieve_processed_frame()

In [7]:
df.head()

,studyId_Alle_celldyn,c_b_wbc,c_b_wvf,c_b_neu,c_b_seg,c_b_bnd,c_b_ig,c_b_lym,c_b_lyme,c_b_vlym,...,c_b_rbcicv,c_b_rbcfmn,c_b_rbcfcv,c_b_rtcfmn,c_b_rtcfcv,c_b_hb,c_b_mch,c_b_mchc,gender,age
322654,4.478707e+09,2.195780,-0.002545,1.894648,1.894648,-46.051702,-46.051702,0.525899,0.525899,-46.051702,...,0.532526,4.420483,2.670660,4.881468,2.589086,1.909950,0.753502,-1.566488,0,77.949802
322655,5.737137e+09,2.105555,-0.005503,1.727456,1.727456,-46.051702,-46.051702,0.669249,0.669249,-46.051702,...,0.605119,4.402454,2.662544,4.906171,2.560887,2.150242,0.596625,-1.551532,0,58.739726
322656,1.138214e+09,1.234867,-0.005151,0.494373,0.494373,-46.051702,-46.051702,0.192552,0.192552,-46.051702,...,0.483746,4.437773,2.553834,4.885163,2.468328,2.152011,0.732980,-1.519682,1,43.673973
322657,3.498087e+09,2.197248,-0.001673,2.124826,2.124826,-46.051702,-46.051702,-0.844491,-0.844491,-46.051702,...,0.408753,4.427309,2.543608,4.859859,2.589011,1.770167,0.644147,-1.544223,0,48.484932
322658,5.075906e+09,3.389597,-0.014272,3.221141,3.166407,0.288669,-46.051702,0.688280,0.688280,-46.051702,...,0.403830,4.473014,2.529976,5.003436,2.658587,1.810239,0.732572,-1.615237,0,52.306849